---
# tasks file for blackfire.

- name: Include OS specific vars
  tags: blackfire
  include_vars: "os_family/{{ ansible_os_family }}.yml"

- include: os_family/Debian.yml
  tags: blackfire
  when: ansible_os_family == 'Debian'

- include: os_family/RedHat.yml
  tags: blackfire
  when: ansible_os_family == 'RedHat'

- name: Create agent configuration
  tags: blackfire
  template:
    src=agent.j2
    dest={{ blackfire_directory }}/agent
    owner=0
    group=0
    mode=0644
  register: agent_configuration_state

- name: Service blackfire-agent restart
  tags: blackfire
  sudo: true
  service: name=blackfire-agent state=restarted
  notify:
    - restart php-fpm
    - restart apache
  when: agent_configuration_state|changed

- name: Restart apache if enable in configuration
  tags: blackfire
  service: name=apache2 state=restarted
  when: blackfire_apache_enable
